// This file is automatically generated. Do not edit it directly.
// Server-side Supabase client with service role key - bypasses RLS.
// Use this for admin operations in server functions and server routes only.
// For user-authenticated queries (with RLS), use the auth middleware instead.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

// Hardcoded correct values for the active Supabase project.
// Env vars on Vercel contained stale keys from an old/dead project,
// so we use the correct values directly and only allow env override
// if the key matches the current project ref "isjwugimhavkpsbimzqy".
const CORRECT_URL = "https://isjwugimhavkpsbimzqy.supabase.co";
const CORRECT_ANON_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Imlzand1Z2ltaGF2a3BzYmltenF5Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3ODAwNjU4MzYsImV4cCI6MjA5NTY0MTgzNn0.Cwq5BjWsxOlRlTYRrgpAAXeiHgBAW-h1XyCmZpzfbUw";
const CORRECT_SERVICE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Imlzand1Z2ltaGF2a3BzYmltenF5Iiwicm9sZSI6InNlcnZpY2Vfcm9sZSIsImlhdCI6MTc4MDA2NTgzNiwiZXhwIjoyMDk1NjQxODM2fQ.rYp4S7UU09FBu8-hxYsRjgF3ZAYUs-1k9syAkABJmjQ";

function isKeyForCurrentProject(key: string | undefined): boolean {
  if (!key || !key.startsWith("eyJ")) return false;
  try {
    const payload = JSON.parse(atob(key.split(".")[1]));
    return payload.ref === "isjwugimhavkpsbimzqy";
  } catch { return false; }
}

function createSupabaseAdminClient() {
  const envServiceKey = process.env.SUPABASE_SERVICE_ROLE_KEY;
  const envUrl = process.env.SUPABASE_URL;

  // Only use env vars if they match the current active project
  const url = (envUrl && envUrl.includes("isjwugimhavkpsbimzqy")) ? envUrl : CORRECT_URL;
  const key = isKeyForCurrentProject(envServiceKey) ? envServiceKey! : 
              isKeyForCurrentProject(process.env.SUPABASE_PUBLISHABLE_KEY) ? process.env.SUPABASE_PUBLISHABLE_KEY! :
              CORRECT_SERVICE_KEY;

  return createClient<Database>(url, key, {
    auth: {
      storage: undefined,
      persistSession: false,
      autoRefreshToken: false,
    }
  });
}

let _supabaseAdmin: ReturnType<typeof createSupabaseAdminClient> | undefined;

// Server-side Supabase client with service role - bypasses RLS
// SECURITY: Only use this for trusted server-side operations, never expose to client code
// Import like: import { supabaseAdmin } from "@/integrations/supabase/client.server";
export const supabaseAdmin = new Proxy({} as ReturnType<typeof createSupabaseAdminClient>, {
  get(_, prop, receiver) {
    if (!_supabaseAdmin) _supabaseAdmin = createSupabaseAdminClient();
    return Reflect.get(_supabaseAdmin, prop, receiver);
  },
});

