// This file is automatically generated. Do not edit it directly.
// Server-side Supabase client with service role key - bypasses RLS.
// Use this for admin operations in server functions and server routes only.
// For user-authenticated queries (with RLS), use the auth middleware instead.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

function createSupabaseAdminClient() {
  let SUPABASE_URL = process.env.SUPABASE_URL;
  let SUPABASE_SERVICE_ROLE_KEY = process.env.SUPABASE_SERVICE_ROLE_KEY;
  let SUPABASE_PUBLISHABLE_KEY = process.env.SUPABASE_PUBLISHABLE_KEY;

  // Auto-resolve placeholder if copied literally from instruction table
  if (SUPABASE_URL === "same as SUPABASE_URL" || !SUPABASE_URL) {
    SUPABASE_URL = "https://isjwugimhavkpsbimzqy.supabase.co";
  }

  const isInvalidServiceKey = !SUPABASE_SERVICE_ROLE_KEY || 
    SUPABASE_SERVICE_ROLE_KEY.includes("copy from") || 
    SUPABASE_SERVICE_ROLE_KEY.includes("Service role key");

  // Fallback to publishable key if service role key is not valid
  const keyToUse = isInvalidServiceKey ? SUPABASE_PUBLISHABLE_KEY : SUPABASE_SERVICE_ROLE_KEY;

  const isInvalidPublishableKey = !keyToUse ||
    keyToUse.includes("same as") ||
    keyToUse.includes("PUBLISHABLE_KEY");

  const finalKey = isInvalidPublishableKey 
    ? "sb_publishable_tDJmK23ZLOBr5uabl1YV5g_5mytdWOc" 
    : keyToUse;

  return createClient<Database>(SUPABASE_URL, finalKey, {
    auth: {
      storage: undefined,
      persistSession: false,
      autoRefreshToken: false,
    }
  });
}

let _supabaseAdmin: ReturnType<typeof createSupabaseAdminClient> | undefined;

// Server-side Supabase client with service role - bypasses RLS
// SECURITY: Only use this for trusted server-side operations, never expose to client code
// Import like: import { supabaseAdmin } from "@/integrations/supabase/client.server";
export const supabaseAdmin = new Proxy({} as ReturnType<typeof createSupabaseAdminClient>, {
  get(_, prop, receiver) {
    if (!_supabaseAdmin) _supabaseAdmin = createSupabaseAdminClient();
    return Reflect.get(_supabaseAdmin, prop, receiver);
  },
});
